#!/usr/bin/env bash
#  Bash script that loops from 1 to 10 displays "bad lack" for the 4th loop iteration,"good lack" for the 8th loop iteration and "Best school" for the other iteration


counter=1

while [ $counter -le 10 ]
do
   if [ $counter -eq 4 ]
   then
      echo "Bad Luck"
   elif [ $counter -eq 8 ]
   then
      echo "Good Luck"
   else
      echo "Best School"
   fi
   ((counter++))
don
